#!/bin/bash

echo "INSTALANDO --> UNIVERSE"
add-apt-repository universe -y &
echo "INSTALANDO --> PIP NO PYTHON3"
apt install python3-pip -y &
echo "INSTALANDO --> PYGAME"
pip3 install pygame&
echo "INSTALANDO --> GIT"
apt install git -y 

echo "CONCLUIDO"